# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41e3f12965eba46fc21d9dff7e217edd4a801b687ae8ab744fa0b5443ca589c01239f960dc43e00e5451f1e9e77359caf2a8256bdf3f326eafb02621d4144dc3

test:
  secret_key_base: a80c13f56914821efa3e818925471bc422a4f69a2727da288bca0ad10c9a79ca5e567f1cbe3677baace9612ebf23a86a49b1af603351f1fa995ea14ae2181abd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
